---
spring:
  config:
    import: "configserver:https://github.com/spring-cloud-services-samples/cook-config"
  application:
    name: cook

encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme

management:
  endpoints:
    web:
      exposure:
        include: '*'
